### PR TITLE
Add allowEmpty

### PR DESCRIPTION
**Pull request by jpSimkins**
New pull request to work with latest version of master to allow auto merge.

This adds the ability to allow empty values while also obeying allowZero.

This is in response to: https://github.com/plentz/jquery-maskmoney/issues/83

### CODE REVIEW

**Comment by alanwillms** [comment]
:+1:

**Comment by alanwillms** [comment]
@plentz Can you please merge this PR?

**Comment by thinkmorebetter** [comment]
:+1:

**Comment by DavidVII** [comment]
:+1:

**Comment by alanwillms** [comment]
@jpSimkins with the following config I have a bug

If I click in the field and click outside it, it will be filled with `0.00`, even if I didn't type anything:

```javascript
$('#my-field').maskMoney({
    allowZero: true,
    allowNegative: true,
    allowEmpty: true,
    defaultZero: false,
    affixesStay: false,
    precision: 2,
    thousands: '',
    decimal: '.'
});
```

**Comment by DavidVII** [comment]
@alanwillms I'm dealing with the same issue. It appears that `allowEmpty` leaves the field empty if the default value is removed. `allowEmpty` works as expected if the field is currently 0. However, if you have *anything* other than the default value, it will fill in the field with 0 since it's the default.

For now, if you want an empty field, replace whatever field has with 0 then delete it. The field will be left empty after that.

**Comment by jpSimkins** [comment]
Yes, that was left that way mostly due to my needs. I wanted to allow empty but leave it as a zero mask unless purposely removed. I will work on adding a new option to have either behavior as I actually need the zero mask on blur and only want empty when specified. I understand the need for both ways so I will work on this when I get a chance (next week or two).Thanks for the information.

**Comment by jpSimkins** [comment]
Ok, this was really easy to fix. Just trying to come up with a decent name for the setting. I was testing with `allowEmptyDefault` but I'm leaning more towards `allowEmptyDefaultBlur` since this is really for the default blur event when no input is entered. As soon as you have input you will have to double delete to get back to empty (like it currently is) as this has already applied the mask and the normal action takes place. This patch is really just for the default value blur event. 

Any suggestions? I would like to keep it with the `allowEmpty` prefix as this keeps it in the scope of the setting.

**Comment by jpSimkins** [comment]
I kept it with `allowEmptyDefault` as this made the most sense. I also set it to `true` by default as the empty value seems implied on empty values. I feel it fits better to set this to false to have the logic I wanted for my project, where I want empty defaulted to the mask then manually removed.

The failed check seems to be due to something in the master build, not my patch.

**Comment by lucasdavila** [comment]
+1

**Comment by akamud** [comment]
So, why hasn't this been merged yet? :shipit:

**Comment by diegommarino** [comment]
:+1: 
Thank you so much!

**Comment by jpSimkins** [comment]
The new core has it's own implementation. This is now obsolete.

**Pull request closed without merging**
