### PR TITLE
Bug when trying to set initial value.

### PR DESCRIPTION
**Pull request by gaetani**
Bug when trying to set a value, using a different decimal separator. This bug is correlated with the following bugs.
#142 #174 #218

### CODE REVIEW

**Comment by aureliosaraiva** [comment]
@gaetani Do you can solve this conflict?

**Comment by gaetani** [comment]
@aureliosaraiva sorry, but which one?

**Comment by gaetani** [comment]
OK, I can fix that

**Comment by aureliosaraiva** [comment]
Thanks @gaetani

**Comment by Kaspary** [comment]
This error still has in current js minified version? 
For me the minified not whorking, but unminified js working normally.

**Pull request merged**
