### PR TITLE
bugfix for Wrong maked values without decimal #124

### PR DESCRIPTION
**Pull request by ghost**
created jsfiddle with some tests and some comments: http://jsfiddle.net/6vyL2v7f/

### CODE REVIEW

**Comment by bryanjimenez** [comment]
I ran into these two tests below. In my opinion when you set the value of the input field to a number you would expect that same value back, for example, setting 000000000123 should give you 123.00 not 1.23. I would not want an item's value in my db to show 100x cheaper by default when masked through the plugin. Again in my opinion whatever input value is set to 'mask' should be numerically equal to when 'unmasked'.


test("with a lot of leading zeroes", function() {
    var input = $("#input1").maskMoney();
    input.val("000000000123");
    input.maskMoney("mask");
    equal(input.val(), "1.23", "removes the unecessary zeroes");
});

test("with negative symbol and a field that doesn't allow negative ", function() {
    var input = $("#input1").maskMoney({allowNegative: false});
    input.val("-123");
    input.maskMoney("mask");
    equal(input.val(), "1.23", "removes negative symbol");
});

**Comment by plentz** [comment]
@ghost thanks a lot for the PR, but I'm going with another approach, since this one will only work if the user generates the html with the same `decimal` character that he used in maskMoney. I want something that can handle the user creating the html with `5.1` and decimal `,` and when he formats it it changes automatically to `5,10`. I already created the tests and they are in master(if you want to try something ;) )

**Comment by plentz** [comment]
btw, keep an eye @ #114, I will notify there when the issue is solved ;)

**Comment by tumpalion** [comment]
Hi **plentz,**

I'm experiencing the same issue as ghost. Has #124 been resolved? I see where there were two commits. when I update i have the same issue.

**Pull request closed without merging**
