### PR TITLE
Update jquery.maskMoney.js

### PR DESCRIPTION
**Pull request by strongui**
Plugin allowed field edit even if field was readOnly = true.

### CODE REVIEW

**Comment by melloware** [comment]
Don't forget Disabled as well as ReadOnly like this guy states..

https://github.com/plentz/jquery-maskmoney/issues/139

**Comment by emaiax** [comment]
@plentz any chance this can be merged any time soon?

**Comment by aureliosaraiva** [comment]
updated!

**Comment by shawnstephens** [comment]
Why was this closed? As far as I can tell maskMoney is still allowing field edit even when readonly is specified. This is contrary to what the readme states should occur.

**Comment by ThalesLudwig** [comment]
I'm still facing the issue, and my plugin is updated. Why is this closed?

**Comment by brunogc** [comment]
The same situation here. I can reproduce this bug, with version 3.1.1 (the most recent).

**Comment by jpSimkins** [comment]
This repo has been broken for over a year now. It sure feels like it's a dead project so I have started moving off of this. Ever since the rewrite it's been unstable. I still use the version before the rewrite as it's more stable (albeit it has it's own bugs). It's closed because this project gets very little attention now by the "team" and I expect it to never be fixed.

**Pull request closed without merging**
