### PR TITLE
Fix bug Precision set 0 and Submit a form with Enter

### PR DESCRIPTION
**Pull request by haifahrul**
1. Fix bug When precision set 0
2. Submit a form with Enter on keyboard

### CODE REVIEW

**Comment by crisdeoliveira** [comment]
Hi friends. Any prediction to correct this @plentz @haifahrul?

**Comment by aureliosaraiva** [comment]
@crisdeoliveira you need make the correction in the folder 'src'

**Comment by crisdeoliveira** [comment]
I'll check, thks @aureliosaraiva.

**Comment by haifahrul** [comment]
Is this solved? @crisdeoliveira

**Pull request closed without merging**
