### PR TITLE
double click selection setting added

### PR DESCRIPTION
**Pull request by kelvah**
doubleClickSelection setting lets users double click the input to
select all its content

### CODE REVIEW

**Comment by kelvah** [comment]
hi @plentz! did you have time to take a look at my pr?
it was somehow difficult to select the content of an input field to clear it. so I added a setting to let the user double click on it to select all.
what you think?

**Comment by kelvah** [comment]
💤

**Comment by aureliosaraiva** [comment]
@kelvah 
can you implement unit test for new feature?

**Comment by kelvah** [comment]
i have pushed the test. would you have a look?

**Comment by aureliosaraiva** [comment]
Thanks.

**Pull request merged**
