### PR TITLE
Using SauceLabs OpenSource 

### PR DESCRIPTION
**Pull request by fassetar**
I wouldn't merge this code outright but take a look at the parts connected to sauce labs the could really help this project.

### CODE REVIEW

**Comment by plentz** [comment]
@fassetar any reason to close this? this was looking promising

**Comment by fassetar** [comment]
Hey @plentz I was just waiting for some feedback ;) Thanks

**Comment by plentz** [comment]
@fassetar if you can, please explain some of the changes that you've made. it will help me understand better and review the PR :)

ps: sorry for taking so long to reply, I'm kinda busy these days

**Comment by fassetar** [comment]
@plentz No worries, I'll try to keep my changes simple and concise.  I'll probably write something in my blog and post back here once I'm done.

**Comment by aureliosaraiva** [comment]
i'll see later.

**Comment by aureliosaraiva** [comment]
Can you resolve this conflict?

**Comment by aureliosaraiva** [comment]
@fassetar thank you

**Pull request closed without merging**
