### PR TITLE
Fix format on unprecision value

### PR DESCRIPTION
**Pull request by danieloprado**
If the value come without the precisian value add zeros to prevent the format mistake

### CODE REVIEW

**Comment by plentz** [comment]
sorry for taking so long to reply. but the tests are failing and I cannot merge that way :(

**Comment by plentz** [comment]
#147

**Comment by plentz** [comment]
@danieloprado thanks a lot for the PR, but I'm going with another approach, since this one will only work if the user generates the html with the same `decimal` character that he used in maskMoney. I want something that can handle the user creating the html with `5.1` and decimal `,` and when he formats it it changes automatically to `5,10`. I already created the tests and they are in master(if you want to try something ;) )

**Comment by plentz** [comment]
btw, keep an eye @ #114, I will notify there when the issue is solved ;)

**Comment by danieloprado** [comment]
Sorry, I don't have much time to expend on it, I will keep my eye on #114 and I will try to fix my code to work with yours. Thanks

**Pull request closed without merging**
